- name : Configure Docker on New Prod-Server-EC2 Instances
  hosts : all
  become: true
  #connection : ssh
  tasks :
  - name: updating apt
    command : sudo apt update
  - name: Install Python Pip
    command : sudo apt install -y python-pip
  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root
  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root
